name: Rust checks
on: [push, pull_request]
jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --locked
      - name: Test
        run: cargo test --locked
